excerpt_separator: "<!--more-->"
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
url: http://www.japandeals.com
title: JapanDeal
author: Lin
tagline: Deals for Japanese in North America
description: "Deals for Japanese in North America" 
plugins:
  - jekyll-seo-tag
logo: /public/favicon/favicon-196x196.png
future: true
social:
  name: Luke Zhao
  links:
    - https://www.facebook.com/lzhaoyilun
    - https://www.linkedin.com/in/lkzhao
    - https://github.com/lkzhao